num_elems: 5
roles:
  - hq
  - troops
  - elites
  - fastattack
  - heavysupport
  - dedicatedtransport
  - flyer
  - lordofwar
  - fortification
detachments:
  - type: patrol
    mandatory:
      - hq: 1,2
        troops: 1,3
    optional:
      - elites: 0,2
        fastattack: 0,2
        heavysupport: 0,2
  - type: battalion
    mandatory:
      - hq: 2,3
        troops: 3,6
    optional:
      - elites: 0,6
        fastattack: 0,3
        heavysupport: 0,3
unit: 
  - name: BiologusPutrifier
    number: 1
    damage: 0.889
    costs: 74
    role: elites
  - name: BlightlordTerminators
    number: 5,10
    damage: 1.667
    costs: 45
    role: elites
  - name: ChaosCultists
    number: 10,40
    damage: 0.56
    costs: 40
    role: troops
  - name: ChaosLandRaider
    number: 1
    damage: 3.241
    costs: 239
    role: heavysupport
  - name: ChaosLord
    number: 1
    damage: 1.157
    costs: 74
    role: hq
  - name: ChaosLordTerminator
    number: 1
    damage: 1.667
    costs: 105
    role: hq
  - name: ChaosPredator
    number: 1
    damage: 3.241
    costs: 90
    role: heavysupport
  - name: ChaosRhino
    number: 1
    damage: 0.519
    costs: 70
    role: dedicatedtransport
  - name: ChaosSpawn
    number: 1,5
    damage: 1.556
    costs: 33
    role: fastattack
  - name: DaemonPrinceNurgle
    number: 1
    damage: 5.185
    costs: 146
    role: hq
  - name: DeathshroudTerminator
    number: 3,6
    damage: 2.778
    costs: 150
    role: elites
  - name: Defiler
    number: 1
    damage: 4.861
    costs: 152
    role: heavysupport
  - name: FoetidBloatDrone
    number: 1
    damage: 5
    costs: 99
    role: fastattack
  - name: FoulBlightSpawn
    number: 1
    damage: 1.458
    costs: 99
    role: elites
  - name: Helbrute
    number: 1
    damage: 4.167
    costs: 72
    role: elites
  - name: LordContagion
    number: 1
    damage: 3.7
    costs: 120
    role: hq
  - name: MalignantPlaguecaster
    number: 1
    damage: 2.222
    costs: 110
    role: hq
  - name: MyphiticBlightHaulers
    number: 1,3
    damage: 1.458
    costs: 85
    role: fastattack
  - name: NoxiousBlightbringer
    number: 1
    damage: 0.926
    costs: 63
    role: elites
  - name: PlagueMarines
    number: 5,20
    damage: 3.036
    costs: 123
    role: troops
  - name: PlagueSurgeon
    number: 1
    damage: 0.833
    costs: 59
    role: elites
  - name: PlagueburstCrawler
    number: 1
    damage: 1.944
    costs: 110
    role: heavysupport
  - name: Possessed
    number: 5,20
    damage: 0.593
    costs: 22
    role: elites
  - name: Poxwalkers
    number: 10,20
    damage: 0.37
    costs: 60
    role: troops
  - name: Sorcerer
    number: 1
    damage: 2.222
    costs: 90
    role: hq
  - name: SorcererTerminator
    number: 1
    damage: 2.222
    costs: 140
    role: hq
  - name: Tallyman
    number: 1
    damage: 0.926
    costs: 60
    role: elites
  - name: Typhus
    number: 1
    damage: 5.56
    costs: 175
    role: hq
  - name: Mortarion
    number: 1
    damage: 14.583
    costs: 470
    role: lordofwar